// Package config reads and writes fluxboost.yaml, the marker file at the
// root of a scaffolded GitOps repo that records the choices made at init
// time — and everything added since — so every fluxboost command stays
// consistent with them and can regenerate what it owns.
package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const FileName = "fluxboost.yaml"

// Tenant records a tenant and, optionally, the external git repo it
// reconciles from instead of the platform repo.
type Tenant struct {
	Name   string `yaml:"name"`
	Repo   string `yaml:"repo,omitempty"`
	Branch string `yaml:"branch,omitempty"`
	Path   string `yaml:"path,omitempty"`
}

// App records a registered application and how it was scaffolded.
type App struct {
	Name            string `yaml:"name"`
	Type            string `yaml:"type"` // deployment | cronjob
	Image           string `yaml:"image"`
	Port            int    `yaml:"port,omitempty"`
	Host            string `yaml:"host,omitempty"`
	Schedule        string `yaml:"schedule,omitempty"`
	ImageAutomation bool   `yaml:"imageAutomation,omitempty"`
}

// Sops records the repo's secrets-encryption setup.
type Sops struct {
	AgeRecipient string `yaml:"ageRecipient"`
}

type Config struct {
	Version            int               `yaml:"version"`
	Provider           string            `yaml:"provider"`
	BaseDomain         string            `yaml:"baseDomain"`
	DomainManagerEmail string            `yaml:"domainManagerEmail"`
	GitURL             string            `yaml:"gitUrl,omitempty"`
	Environments       []string          `yaml:"environments"`
	Services           []string          `yaml:"services"`
	Vars               map[string]string `yaml:"vars,omitempty"`
	Sops               *Sops             `yaml:"sops,omitempty"`
	Tenants            []Tenant          `yaml:"tenants,omitempty"`
	Apps               []App             `yaml:"apps,omitempty"`
}

func (c *Config) HasEnv(env string) bool {
	for _, e := range c.Environments {
		if e == env {
			return true
		}
	}
	return false
}

func (c *Config) HasService(name string) bool {
	for _, s := range c.Services {
		if s == name {
			return true
		}
	}
	return false
}

func (c *Config) Tenant(name string) (Tenant, bool) {
	for _, t := range c.Tenants {
		if t.Name == name {
			return t, true
		}
	}
	return Tenant{}, false
}

func (c *Config) App(name string) (App, bool) {
	for _, a := range c.Apps {
		if a.Name == name {
			return a, true
		}
	}
	return App{}, false
}

func Load(repoPath string) (*Config, error) {
	b, err := os.ReadFile(filepath.Join(repoPath, FileName))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("%s not found in %s — run `fluxboost init` first", FileName, repoPath)
		}
		return nil, err
	}
	var c Config
	if err := yaml.Unmarshal(b, &c); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", FileName, err)
	}
	// Backfill defaults for repos written by older fluxboost versions.
	for i := range c.Apps {
		if c.Apps[i].Type == "" {
			c.Apps[i].Type = "deployment"
		}
	}
	return &c, nil
}

func (c *Config) Save(repoPath string) error {
	b, err := yaml.Marshal(c)
	if err != nil {
		return err
	}
	header := []byte("# Generated by fluxboost. Records the choices made at init time (and\n# additions since) so every fluxboost command stays consistent with them.\n")
	return os.WriteFile(filepath.Join(repoPath, FileName), append(header, b...), 0o644)
}
